import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import VSL from '../components/vsl'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>AI VSL Generator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <VSL/>
      </main>
    </div>
  )
}
